name: lint

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install
        run: |
          python -m pip install -U pip
          pip install -e ".[dev]"

      - name: Ruff
        run: |
          ruff check .

      - name: Black
        run: |
          black --check .

      - name: Mypy
        run: |
          mypy src
