name: microbench

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 0"

jobs:
  microbench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install
        run: |
          python -m pip install -U pip
          pip install -e ".[dev]"

      - name: Run microbench pipeline
        run: |
          python -c "from tig.workflows.pipelines import run_microbench; run_microbench()"
